# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogSpectralClustering.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogSpectralClustering(object):
    def setupUi(self, dialogSpectralClustering):
        dialogSpectralClustering.setObjectName("dialogSpectralClustering")
        dialogSpectralClustering.resize(294, 324)
        self.gridLayout = QtWidgets.QGridLayout(dialogSpectralClustering)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(dialogSpectralClustering)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dialogSpectralClustering_n_clusterTextBox = QtWidgets.QTextEdit(dialogSpectralClustering)
        self.dialogSpectralClustering_n_clusterTextBox.setObjectName("dialogSpectralClustering_n_clusterTextBox")
        self.gridLayout.addWidget(self.dialogSpectralClustering_n_clusterTextBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(dialogSpectralClustering)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.dialogSpectralClustering_n_neighborsTextBox = QtWidgets.QTextEdit(dialogSpectralClustering)
        self.dialogSpectralClustering_n_neighborsTextBox.setObjectName("dialogSpectralClustering_n_neighborsTextBox")
        self.gridLayout.addWidget(self.dialogSpectralClustering_n_neighborsTextBox, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(dialogSpectralClustering)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.dialogSpectralClustering_affinityComboBox = QtWidgets.QComboBox(dialogSpectralClustering)
        self.dialogSpectralClustering_affinityComboBox.setObjectName("dialogSpectralClustering_affinityComboBox")
        self.dialogSpectralClustering_affinityComboBox.addItem("")
        self.dialogSpectralClustering_affinityComboBox.addItem("")
        self.gridLayout.addWidget(self.dialogSpectralClustering_affinityComboBox, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(dialogSpectralClustering)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.dialogSpectralClustering_n_initTextBox = QtWidgets.QTextEdit(dialogSpectralClustering)
        self.dialogSpectralClustering_n_initTextBox.setObjectName("dialogSpectralClustering_n_initTextBox")
        self.gridLayout.addWidget(self.dialogSpectralClustering_n_initTextBox, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(dialogSpectralClustering)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.dialogSpectralClustering_assign_labelsComboBox = QtWidgets.QComboBox(dialogSpectralClustering)
        self.dialogSpectralClustering_assign_labelsComboBox.setObjectName("dialogSpectralClustering_assign_labelsComboBox")
        self.dialogSpectralClustering_assign_labelsComboBox.addItem("")
        self.dialogSpectralClustering_assign_labelsComboBox.addItem("")
        self.dialogSpectralClustering_assign_labelsComboBox.addItem("")
        self.gridLayout.addWidget(self.dialogSpectralClustering_assign_labelsComboBox, 4, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(dialogSpectralClustering)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 2)

        self.retranslateUi(dialogSpectralClustering)
        self.buttonBox.accepted.connect(dialogSpectralClustering.accept) # type: ignore
        self.buttonBox.rejected.connect(dialogSpectralClustering.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialogSpectralClustering)

    def retranslateUi(self, dialogSpectralClustering):
        _translate = QtCore.QCoreApplication.translate
        dialogSpectralClustering.setWindowTitle(_translate("dialogSpectralClustering", "Spectral Clustering"))
        self.label.setText(_translate("dialogSpectralClustering", "Number of Clusters, int, Default value is 8"))
        self.dialogSpectralClustering_n_clusterTextBox.setHtml(_translate("dialogSpectralClustering", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">8</p></body></html>"))
        self.label_2.setText(_translate("dialogSpectralClustering", "Number of Neighbors, Default value is 10"))
        self.dialogSpectralClustering_n_neighborsTextBox.setHtml(_translate("dialogSpectralClustering", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10</p></body></html>"))
        self.label_3.setText(_translate("dialogSpectralClustering", "Affinity Type, str, Default value is \"rbf\""))
        self.dialogSpectralClustering_affinityComboBox.setItemText(0, _translate("dialogSpectralClustering", "rbf"))
        self.dialogSpectralClustering_affinityComboBox.setItemText(1, _translate("dialogSpectralClustering", "nearest_neighbors"))
        self.label_4.setText(_translate("dialogSpectralClustering", "Number of Initializers, int, Default value is 10"))
        self.dialogSpectralClustering_n_initTextBox.setHtml(_translate("dialogSpectralClustering", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10</p></body></html>"))
        self.label_5.setText(_translate("dialogSpectralClustering", "Label Types to be Assigned, Default value is kmeans"))
        self.dialogSpectralClustering_assign_labelsComboBox.setItemText(0, _translate("dialogSpectralClustering", "kmeans"))
        self.dialogSpectralClustering_assign_labelsComboBox.setItemText(1, _translate("dialogSpectralClustering", "discretize"))
        self.dialogSpectralClustering_assign_labelsComboBox.setItemText(2, _translate("dialogSpectralClustering", "cluster_qr"))
