# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogHierarchialClustering.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogHierarchialClustering(object):
    def setupUi(self, dialogHierarchialClustering):
        dialogHierarchialClustering.setObjectName("dialogHierarchialClustering")
        dialogHierarchialClustering.resize(271, 170)
        self.gridLayout = QtWidgets.QGridLayout(dialogHierarchialClustering)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(dialogHierarchialClustering)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dialogHierarhialClustering_n_clusterTextBox = QtWidgets.QTextEdit(dialogHierarchialClustering)
        self.dialogHierarhialClustering_n_clusterTextBox.setObjectName("dialogHierarhialClustering_n_clusterTextBox")
        self.gridLayout.addWidget(self.dialogHierarhialClustering_n_clusterTextBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(dialogHierarchialClustering)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.dialogHierarchialClustering_affinityComboBox = QtWidgets.QComboBox(dialogHierarchialClustering)
        self.dialogHierarchialClustering_affinityComboBox.setObjectName("dialogHierarchialClustering_affinityComboBox")
        self.dialogHierarchialClustering_affinityComboBox.addItem("")
        self.dialogHierarchialClustering_affinityComboBox.addItem("")
        self.dialogHierarchialClustering_affinityComboBox.addItem("")
        self.dialogHierarchialClustering_affinityComboBox.addItem("")
        self.dialogHierarchialClustering_affinityComboBox.addItem("")
        self.dialogHierarchialClustering_affinityComboBox.addItem("")
        self.gridLayout.addWidget(self.dialogHierarchialClustering_affinityComboBox, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(dialogHierarchialClustering)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.dialogHierarchialClustering_linkageComboBox = QtWidgets.QComboBox(dialogHierarchialClustering)
        self.dialogHierarchialClustering_linkageComboBox.setObjectName("dialogHierarchialClustering_linkageComboBox")
        self.dialogHierarchialClustering_linkageComboBox.addItem("")
        self.dialogHierarchialClustering_linkageComboBox.addItem("")
        self.dialogHierarchialClustering_linkageComboBox.addItem("")
        self.dialogHierarchialClustering_linkageComboBox.addItem("")
        self.gridLayout.addWidget(self.dialogHierarchialClustering_linkageComboBox, 2, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(dialogHierarchialClustering)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 2)

        self.retranslateUi(dialogHierarchialClustering)
        self.buttonBox.accepted.connect(dialogHierarchialClustering.accept) # type: ignore
        self.buttonBox.rejected.connect(dialogHierarchialClustering.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialogHierarchialClustering)

    def retranslateUi(self, dialogHierarchialClustering):
        _translate = QtCore.QCoreApplication.translate
        dialogHierarchialClustering.setWindowTitle(_translate("dialogHierarchialClustering", "Hierarchial Clustering"))
        self.label.setText(_translate("dialogHierarchialClustering", "Number of Clusters, int, Default value is 2"))
        self.dialogHierarhialClustering_n_clusterTextBox.setHtml(_translate("dialogHierarchialClustering", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2</p></body></html>"))
        self.label_2.setText(_translate("dialogHierarchialClustering", "Affinity Type, Default value is euclidean"))
        self.dialogHierarchialClustering_affinityComboBox.setItemText(0, _translate("dialogHierarchialClustering", "euclidean"))
        self.dialogHierarchialClustering_affinityComboBox.setItemText(1, _translate("dialogHierarchialClustering", "l1"))
        self.dialogHierarchialClustering_affinityComboBox.setItemText(2, _translate("dialogHierarchialClustering", "l2"))
        self.dialogHierarchialClustering_affinityComboBox.setItemText(3, _translate("dialogHierarchialClustering", "manhattan"))
        self.dialogHierarchialClustering_affinityComboBox.setItemText(4, _translate("dialogHierarchialClustering", "cosine"))
        self.dialogHierarchialClustering_affinityComboBox.setItemText(5, _translate("dialogHierarchialClustering", "precomputed"))
        self.label_3.setText(_translate("dialogHierarchialClustering", "Linkage Type, Default value is ward"))
        self.dialogHierarchialClustering_linkageComboBox.setItemText(0, _translate("dialogHierarchialClustering", "ward"))
        self.dialogHierarchialClustering_linkageComboBox.setItemText(1, _translate("dialogHierarchialClustering", "complete"))
        self.dialogHierarchialClustering_linkageComboBox.setItemText(2, _translate("dialogHierarchialClustering", "average"))
        self.dialogHierarchialClustering_linkageComboBox.setItemText(3, _translate("dialogHierarchialClustering", "single"))
