# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogDBSCAN.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogDBSCAN(object):
    def setupUi(self, dialogDBSCAN):
        dialogDBSCAN.setObjectName("dialogDBSCAN")
        dialogDBSCAN.resize(235, 221)
        self.gridLayout = QtWidgets.QGridLayout(dialogDBSCAN)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(dialogDBSCAN)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dialogDBSCAN_epsTextBox = QtWidgets.QTextEdit(dialogDBSCAN)
        self.dialogDBSCAN_epsTextBox.setObjectName("dialogDBSCAN_epsTextBox")
        self.gridLayout.addWidget(self.dialogDBSCAN_epsTextBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(dialogDBSCAN)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.dialogDBSCAN_min_samplesTextBox = QtWidgets.QTextEdit(dialogDBSCAN)
        self.dialogDBSCAN_min_samplesTextBox.setObjectName("dialogDBSCAN_min_samplesTextBox")
        self.gridLayout.addWidget(self.dialogDBSCAN_min_samplesTextBox, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(dialogDBSCAN)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.dialogDBSCAN_algorithmComboBox = QtWidgets.QComboBox(dialogDBSCAN)
        self.dialogDBSCAN_algorithmComboBox.setObjectName("dialogDBSCAN_algorithmComboBox")
        self.dialogDBSCAN_algorithmComboBox.addItem("")
        self.dialogDBSCAN_algorithmComboBox.addItem("")
        self.dialogDBSCAN_algorithmComboBox.addItem("")
        self.dialogDBSCAN_algorithmComboBox.addItem("")
        self.gridLayout.addWidget(self.dialogDBSCAN_algorithmComboBox, 2, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(dialogDBSCAN)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 2)

        self.retranslateUi(dialogDBSCAN)
        self.buttonBox.accepted.connect(dialogDBSCAN.accept) # type: ignore
        self.buttonBox.rejected.connect(dialogDBSCAN.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialogDBSCAN)

    def retranslateUi(self, dialogDBSCAN):
        _translate = QtCore.QCoreApplication.translate
        dialogDBSCAN.setWindowTitle(_translate("dialogDBSCAN", "DBSCAN"))
        self.label.setText(_translate("dialogDBSCAN", "EPS Value, float, Default value is 0.5"))
        self.dialogDBSCAN_epsTextBox.setHtml(_translate("dialogDBSCAN", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.5</p></body></html>"))
        self.label_2.setText(_translate("dialogDBSCAN", "Minimum Number of Samples, int, Default value is 5"))
        self.dialogDBSCAN_min_samplesTextBox.setHtml(_translate("dialogDBSCAN", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5</p></body></html>"))
        self.label_3.setText(_translate("dialogDBSCAN", "Algorithm Type, Default value is auto"))
        self.dialogDBSCAN_algorithmComboBox.setItemText(0, _translate("dialogDBSCAN", "auto"))
        self.dialogDBSCAN_algorithmComboBox.setItemText(1, _translate("dialogDBSCAN", "ball_tree"))
        self.dialogDBSCAN_algorithmComboBox.setItemText(2, _translate("dialogDBSCAN", "kd_tree"))
        self.dialogDBSCAN_algorithmComboBox.setItemText(3, _translate("dialogDBSCAN", "brute"))
