# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogAffinityPropagation.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogAffinityPropagation(object):
    def setupUi(self, dialogAffinityPropagation):
        dialogAffinityPropagation.setObjectName("dialogAffinityPropagation")
        dialogAffinityPropagation.resize(265, 272)
        self.gridLayout = QtWidgets.QGridLayout(dialogAffinityPropagation)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(dialogAffinityPropagation)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dialogAffinityPropagation_dampingTextBox = QtWidgets.QTextEdit(dialogAffinityPropagation)
        self.dialogAffinityPropagation_dampingTextBox.setMouseTracking(False)
        self.dialogAffinityPropagation_dampingTextBox.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.dialogAffinityPropagation_dampingTextBox.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.dialogAffinityPropagation_dampingTextBox.setObjectName("dialogAffinityPropagation_dampingTextBox")
        self.gridLayout.addWidget(self.dialogAffinityPropagation_dampingTextBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(dialogAffinityPropagation)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.dialogAffinityPropagation_max_iterTextBox = QtWidgets.QTextEdit(dialogAffinityPropagation)
        self.dialogAffinityPropagation_max_iterTextBox.setObjectName("dialogAffinityPropagation_max_iterTextBox")
        self.gridLayout.addWidget(self.dialogAffinityPropagation_max_iterTextBox, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(dialogAffinityPropagation)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.dialogAffinityPropagation_convergence_iterTextBox = QtWidgets.QTextEdit(dialogAffinityPropagation)
        self.dialogAffinityPropagation_convergence_iterTextBox.setObjectName("dialogAffinityPropagation_convergence_iterTextBox")
        self.gridLayout.addWidget(self.dialogAffinityPropagation_convergence_iterTextBox, 2, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(dialogAffinityPropagation)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 2)

        self.retranslateUi(dialogAffinityPropagation)
        self.buttonBox.accepted.connect(dialogAffinityPropagation.accept) # type: ignore
        self.buttonBox.rejected.connect(dialogAffinityPropagation.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialogAffinityPropagation)

    def retranslateUi(self, dialogAffinityPropagation):
        _translate = QtCore.QCoreApplication.translate
        dialogAffinityPropagation.setWindowTitle(_translate("dialogAffinityPropagation", "Affinity Propagation"))
        self.label.setText(_translate("dialogAffinityPropagation", "Damping Amount, float, Default value is 0.5"))
        self.dialogAffinityPropagation_dampingTextBox.setHtml(_translate("dialogAffinityPropagation", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.5</p></body></html>"))
        self.label_2.setText(_translate("dialogAffinityPropagation", "Maximum Number of Iterations, int, Default value is 200"))
        self.dialogAffinityPropagation_max_iterTextBox.setHtml(_translate("dialogAffinityPropagation", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">200</p></body></html>"))
        self.label_3.setText(_translate("dialogAffinityPropagation", "Convergence Iterations, int, Default value is 15"))
        self.dialogAffinityPropagation_convergence_iterTextBox.setHtml(_translate("dialogAffinityPropagation", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">15</p></body></html>"))
